baseURL = "https://jze.us"
title = "蜀山小筑"
theme = "hugo-notepadium"
copyright = "©2021 蜀山小筑."

languageCode = "zh"  # for the RSS generation
defaultContentLanguage = "zh"

hasCJKLanguage = true

enableRobotsTXT = true
toc = true                                                                            # 是否开启目录
autoCollapseToc = true   # Auto expand and collapse toc                              # 目录自动展开/折叠
fancybox = true           # see https://github.com/fancyapps/fancybox  
moreMeta = true




publishDir = "docs"
# Enable Disqus
#disqusShortname = "shu-shan-xiao-zhu"

# Google Analytics
#googleAnalytics = "UA-123-45"

[markup.highlight]
codeFences = true
noClasses = false

[markup.goldmark.renderer]
unsafe = true  # enable raw HTML in Markdown

[params]
style = "auto"  # default: auto. light: light theme, dark: dark theme, auto: based on system.
dateFormat = "Monday, January 2, 2006"  # if unset, default is "2006-01-02"
logo = "/img/logo.png"  # if you have a logo png
slogan = "「少即是多」"
license = "版权声明：如果转发请带上本文链接和注明来源。"  # CC License
fullRss = false # Puts entire HTML post into rss 'description' tag. If unset, default is false.


[params.comments]
enable = true  # En/Disable comments globally, default: false. You can always enable comments on per page.

[params.math]
enable = true  # optional: true, false. Enable globally, default: false. You can always enable math on per page.
use = "katex"  # option: "katex", "mathjax". default: "katex"

[params.syntax]
use = "none"  # builtin: "prismjs", "hljs". "none" means Chroma
theme = "github" # dracula
darkTheme = "dracula"  # apply this theme in dark mode xcode-dark

[params.share]
enable = false
addThisId = ""
inlineToolId = ""


# custom navigation items

[[params.nav.custom]]
title = "主页"
url = "/"
[[params.nav.custom]]
title = "标签"
url = "/tags"
[[params.nav.custom]]
title = "分类"
url = "/categories"
[[params.nav.custom]]
title = "关于我"
url = "/about"

[params.profile]
  enable = true
  avatar = "/img/avatar.jpg"
  name = "愚道"
  bio = "求知若渴，虚心若愚"  # support markdown syntax
# twitter = "https://twitter.com/"  # https://twitter.com/XXX
  github = "YALEAX"  # https://github.com/XXX
#  docker = "XXX"  # https://hub.docker.com/u/XXX
  email = "Qu@JzE.us"  # mailto:XX	X@mail.com

# for chinese
[params.beian]
  icp = ""     
  gongan = ""    
  code = ""    
